In [1]:
#Import library

import numpy as np

#if we use import numpy only, we would have to use numpy.function each time, this way we can simply use np.function

### Arrays:

In [2]:
#A 1D numpy ndarray is an optimized list for vector operations.
#Numpy is written in the C language making it faster and more optimized

In [6]:
#Range equivalent: Uses same logic and syntax as the generic list

print(range(4))

#This is already better because we do not have to cast it to a list or something else to be visible
print(np.arange(4))

print(list(range(1,4)))
print(np.arange(1,4))

print(list(range(1,10,2)))
print(np.arange(1,10,2))

range(0, 4)
[0 1 2 3]
[1, 2, 3]
[1 2 3]
[1, 3, 5, 7, 9]
[1 3 5 7 9]


In [7]:
#A numpy array does not store Python int,float values, instead it stores efficient C++ style ints and floats
l = list(range(4))
print(type(l[0]))

n = np.arange(4)
print(type(n[0]))

<class 'int'>
<class 'numpy.int64'>


In [8]:
#For loops on numpy arrays work the exact same way as other iterables

#they can easily be converted to other acceptable basic collection types
n = np.arange(4)
print(list(n))
print(tuple(n))

[0, 1, 2, 3]
(0, 1, 2, 3)


In [9]:
#Initializing a list:
#We can create it from another iterable

n1 = np.array([1,2,3,4]) #From list
n2 = np.array((1,2,3,4)) #From tuple

In [15]:
#Unlike a list, every element of ndarray must be of same type, if it isn't then they are upcasted by the function to be of the same type

n3 = np.array([1,2,3,4.4]) #Upcasted to floats
print(type(n3[0]))
print(n3)

#If there is a string/char, the numerics will get upcasted to string/char

<class 'numpy.float64'>
[1.  2.  3.  4.4]


In [17]:
#Array vs List operations:

l = [1,2,3,4]
n = np.array(l)

print(l*3) #Repetition in list
print(n*3) #Scalar multiplication

#print(l+1) #No such thing for lists
print(n+1) #Addition to each element

print(l + l) #Concatenation in list
print(n + n) #Vector sum

[1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4]
[ 3  6  9 12]
[2 3 4 5]
[1, 2, 3, 4, 1, 2, 3, 4]
[2 4 6 8]


In [23]:
#Array vs List indexing,slicing and views:

#Indexing format is same

l = list(range(10))
n = np.arange(10)

print(l[2:6])
print(n[2:6])

l[2:6] = [-8] #Replaces whole slice with a -8
print(l)

n[2:6] = -8
print(n) #Since slicing in arrays are views, it changes each value in that view to -8

#So if you assign a variable to the view and alter the new variable, the original one gets changed as well
print(n)
n2 = n[:3]
n2*=2
print(n2)
print(n)

#So you need to use copies
print(n)
n2 = n[:3].copy()
n2*=2
print(n2)
print(n)

[2, 3, 4, 5]
[2 3 4 5]
[0, 1, -8, 6, 7, 8, 9]
[ 0  1 -8 -8 -8 -8  6  7  8  9]
[ 0  1 -8 -8 -8 -8  6  7  8  9]
[  0   2 -16]
[  0   2 -16  -8  -8  -8   6   7   8   9]
[  0   2 -16  -8  -8  -8   6   7   8   9]
[  0   4 -32]
[  0   2 -16  -8  -8  -8   6   7   8   9]


In [40]:
#N-Dimensional Arrays:

#We can create multi dimensional arrays using list of list of list.. or tuple of tuple of tuple..

a = np.array([[1,2,3,0],[4,5,6,0],[7,8,9,0]])

print(a.ndim) #Gives number of dimensions. Equivalent to len of array.shape

print(a.shape) #Gives size of all dimensions

#We can also create multi dimensional arrays by reshaping
#reshape function returns a copy so no change to the original array. It could be a view or copy of the original array so changes to it 
    #changes original depending on what it is

a = np.arange(12)
a2 = a.reshape(3,4) #parameters are size of dim1,size of dim2,size of dim3,....
print(a2)

#You can use -1 as a filler when using reshape asking the function to figure out the value for us. -1 stands for whatever possible value based on element length. 
#Note we can only input -1 once in the reshape function

print(a.reshape(3,-1))

2
(3, 4)
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [34]:
#Useful Numpy Array Initialzing functions

val = 3.14

dim1 = 3
dim2 = 4
dim3 = 2

N = 5

A = np.ones((dim1,dim2,dim3)) #Array of 1.0s of shape specified. Specified shape must be in tuple form

B = np.zeros((dim1,dim2,dim3)) #Array of 0.0s of shape specified. Specified shape must be in tuple form

C = np.full((dim1,dim2,dim3),val) #Array of vals of shape specified. Specified shape must be in tuple form

D = np.eye(N) #NxN identity matrix

E = np.identity(N) #NxN identity matrix

In [52]:
#2D Slicing of Arrays:
a1 = np.arange(15).reshape(3,5)
print(a1)

print(a1[1:,:3]) #The dimensions are separated by ,

#Changing values using list
a1[1:,:3] = 10000
print(a1)

#Only indexing/slicing on first dimension
print(a1[1:])
print(a1[1])

#Getting a specific element
print(a1[1][2]) #Equivalent to a1[1,2]

#Getting all rows and condition on columns
print(a1[:,1:3])

#Getting all columns and condition on rows
print(a1[1:3,:])

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[ 5  6  7]
 [10 11 12]]
[[    0     1     2     3     4]
 [10000 10000 10000     8     9]
 [10000 10000 10000    13    14]]
[[10000 10000 10000     8     9]
 [10000 10000 10000    13    14]]
[10000 10000 10000     8     9]
10000
[[    1     2]
 [10000 10000]
 [10000 10000]]
[[10000 10000 10000     8     9]
 [10000 10000 10000    13    14]]


In [56]:
#Boolean Indexing
#The True values tell us which index to keep and False is excluded

a1 = np.arange(15).reshape(3,5)
print(a1)

f = [True, False, True]

print(a1[f])

a1[f]*=-1
print(a1)

print(a1[:,[True, True, False,False,False]])

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[ 0  1  2  3  4]
 [10 11 12 13 14]]
[[  0  -1  -2  -3  -4]
 [  5   6   7   8   9]
 [-10 -11 -12 -13 -14]]
[[  0  -1]
 [  5   6]
 [-10 -11]]


In [66]:
#Equality, Inequality and Relational Operators:

a1 = np.arange(15).reshape(3,5)
print(a1<10)

#We can combine it with boolean indexing to get results
a1[a1<10] *= -1
print(a1)

#& is used for and, | is used for or, ^ for xor and ~ for invert
print((a1>10) & (a1<12)) #And
print((a1<2) | (a1>12)) #Or
print(~(a1<0)) #Negation/Invert

[[ True  True  True  True  True]
 [ True  True  True  True  True]
 [False False False False False]]
[[ 0 -1 -2 -3 -4]
 [-5 -6 -7 -8 -9]
 [10 11 12 13 14]]
[[False False False False False]
 [False False False False False]
 [False  True False False False]]
[[ True  True  True  True  True]
 [ True  True  True  True  True]
 [False False False  True  True]]
[[ True False False False False]
 [False False False False False]
 [ True  True  True  True  True]]


In [69]:
#Integer Indexing Aka Fancy Indexing
#Especially useful in chaging the order of row/columns or creating duplicate rows/columns
#Will utilize double brackets [[]]

a = np.arange(15).reshape(3,5)
print(a)

print(a[[2,0]]) #Row 2 followed by 0

print(a[:,[4,2,1]]) #all rows, column 4 followed by 2 followed by 1

#We can create 1D array of select vaues from 2D array using same length lists
print(a[[0,2,1],[4,2,1]]) #1D array of values at 0,4 and 2,2 and 1,1

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[10 11 12 13 14]
 [ 0  1  2  3  4]]
[[ 4  2  1]
 [ 9  7  6]
 [14 12 11]]
[ 4 12  6]


### Random Module: