In [3]:
import numpy as np
import pandas as pd

In [14]:
frequents = pd.DataFrame()
frequents["drinker"] = ["A","B","C","A","D","B"]
frequents["bar"] = [1,1,2,2,3,3]

sells = pd.DataFrame()
sells["beer"] = ["V","X","Y","Z","V","X","Z"]
sells["bar"] = [1,1,1,1,2,2,3]

likes = pd.DataFrame()
likes["drinker"] = ["A","B","C","D","E","A","E","D","B","C"]
likes["beer"] = ["V","V","V","V","V","Z","Z","X","Y","Y"]

In [15]:
frequents

drinker  bar
0       A    1
1       B    1
2       C    2
3       A    2
4       D    3
5       B    3

In [16]:
sells

beer  bar
0    V    1
1    X    1
2    Y    1
3    Z    1
4    V    2
5    X    2
6    Z    3

In [17]:
likes

drinker beer
0       A    V
1       B    V
2       C    V
3       D    V
4       E    V
5       A    Z
6       E    Z
7       D    X
8       B    Y
9       C    Y

In [18]:
'''
select * from sells a
LEFT JOIN frequents b
on a.bar=b.bar
'''
combo1 = sells.merge(frequents,how="left",on="bar")
combo1

beer  bar drinker
0     V    1       A
1     V    1       B
2     X    1       A
3     X    1       B
4     Y    1       A
5     Y    1       B
6     Z    1       A
7     Z    1       B
8     V    2       C
9     V    2       A
10    X    2       C
11    X    2       A
12    Z    3       D
13    Z    3       B

In [ ]:
'''
select distinct(drinker) from
(
select * from likes l
left join 
(
select * from sells a
LEFT JOIN frequents b
on a.bar=b.bar
) t
on l.drinker=t.drinker and l.beer = t.beer
)
where bar is not null
'''
likes.merge(combo1,how="left",on=("drinker","beer"))

In [ ]:
SELECT *,
CASE WHEN (name in ('Sahil','Kayla')) THEN 'Friend of Mike'
ELSE 'Not Friend of Mike'
END AS "Friend of Mike"
FROM Drinkers

In [20]:
import numpy as np
import pandas as pd
from datetime import datetime
from sklearn.decomposition import PCA

In [2]:
fullYCweb = pd.read_html("https://goo.gl/j97141")

IndexError: list index out of range

In [9]:
YCdata = fullYCweb[0]

In [10]:
YCdata['Date'] =YCdata['Date'].astype('datetime64')
YCdata

Date  20 YR  30 YR  Extrapolation Factor  8 WEEKS BANK DISCOUNT  \
0   1990-01-02    NaN    NaN                   NaN                    NaN   
1   1990-01-03    NaN    NaN                   NaN                    NaN   
2   1990-01-04    NaN    NaN                   NaN                    NaN   
3   1990-01-05    NaN    NaN                   NaN                    NaN   
4   1990-01-08    NaN    NaN                   NaN                    NaN   
..         ...    ...    ...                   ...                    ...   
295 1991-03-08    NaN    NaN                   NaN                    NaN   
296 1991-03-11    NaN    NaN                   NaN                    NaN   
297 1991-03-12    NaN    NaN                   NaN                    NaN   
298 1991-03-13    NaN    NaN                   NaN                    NaN   
299 1991-03-14    NaN    NaN                   NaN                    NaN   

     COUPON EQUIVALENT  17 WEEKS BANK DISCOUNT  COUPON EQUIVALENT.1  \
0                  NaN                     NaN                  NaN   
1                  NaN                     NaN                  NaN   
2                  NaN                     NaN                  NaN   
3                  NaN                     NaN                  NaN   
4                  NaN                     NaN                  NaN   
..                 ...                     ...                  ...   
295                NaN                     NaN                  NaN   
296                NaN                     NaN                  NaN   
297                NaN                     NaN                  NaN   
298                NaN                     NaN                  NaN   
299                NaN                     NaN                  NaN   

     52 WEEKS BANK DISCOUNT  COUPON EQUIVALENT.2  ...  4 Mo  6 Mo  1 Yr  2 Yr  \
0                       NaN                  NaN  ...   NaN  7.89  7.81  7.87   
1                       NaN                  NaN  ...   NaN  7.94  7.85  7.94   
2                       NaN                  NaN  ...   NaN  7.90  7.82  7.92   
3                       NaN                  NaN  ...   NaN  7.85  7.79  7.90   
4                       NaN                  NaN  ...   NaN  7.88  7.81  7.90   
..                      ...                  ...  ...   ...   ...   ...   ...   
295                     NaN                  NaN  ...   NaN  6.25  6.41  7.08   
296                     NaN                  NaN  ...   NaN  6.21  6.37  7.05   
297                     NaN                  NaN  ...   NaN  6.19  6.38  7.07   
298                     NaN                  NaN  ...   NaN  6.12  6.30  7.00   
299                     NaN                  NaN  ...   NaN  6.04  6.26  6.95   

     3 Yr  5 Yr  7 Yr  10 Yr  20 Yr  30 Yr  
0    7.90  7.87  7.98   7.94    NaN   8.00  
1    7.96  7.92  8.04   7.99    NaN   8.04  
2    7.93  7.91  8.02   7.98    NaN   8.04  
3    7.94  7.92  8.03   7.99    NaN   8.06  
4    7.95  7.92  8.05   8.02    NaN   8.09  
..    ...   ...   ...    ...    ...    ...  
295  7.35  7.77  8.01   8.13    NaN   8.30  
296  7.30  7.71  7.94   8.06    NaN   8.23  
297  7.33  7.74  7.98   8.09    NaN   8.26  
298  7.23  7.67  7.91   8.02    NaN   8.20  
299  7.19  7.64  7.90   8.02    NaN   8.20  

[300 rows x 23 columns]

In [18]:
df = pd.concat([YCdata["Date"],YCdata.iloc[:,14:21],YCdata["30 Yr"]],axis=1)

In [19]:
df.rename(columns={'1 mo': 1/12,
'3 mo': 1/4, '6 mo': 1/2, '1 yr': 1,
'2 yr': 2, '3 yr': 3, '5 yr': 5, '7 yr': 7, '10 yr': 10, '20 yr': 20, '30 yr': 30}, inplace=True)

In [23]:
pcaout = PCA(n_components=8)

In [24]:
pcaout.fit(df.drop('Date', axis=1))

PCA(n_components=8)

In [25]:
pcaout.explained_variance_ratio_

array([9.25069269e-01, 6.52599156e-02, 8.73328259e-03, 3.37160333e-04,
       2.55022188e-04, 1.98101322e-04, 9.54453142e-05, 5.18032917e-05])

In [26]:
pcaout.components_[0]

array([-0.4801615 , -0.48537917, -0.42692001, -0.38256614, -0.2923779 ,
       -0.2376041 , -0.20148819, -0.15065328])

In [27]:
pcaout.explained_variance_ #Eigenvalues

array([1.79047031e+00, 1.26310478e-01, 1.69032565e-02, 6.52573364e-04,
       4.93595098e-04, 3.83424839e-04, 1.84734275e-04, 1.00265200e-04])

In [47]:
newshift = np.array([0.01,
             0.01, 0.07, 0.05, 0.05, 0.03, 0.03, 0.04])
pcaout.transform(newshift.reshape(1, -1))

array([[21.17124894,  8.68251172,  0.27227326,  0.30608084,  0.14286587,
         0.05568228, -0.12067131,  0.23265442]])

In [49]:
newshift.reshape(1, -1)@pcaout.components_

array([[-0.07077381,  0.02062821,  0.01271609,  0.06374167, -0.04200738,
        -0.00323441,  0.01750028, -0.04194644]])

In [42]:
pcaout.components_@newshift.reshape(-1, 1)

array([[-0.09248591],
       [-0.04679088],
       [ 0.04299296],
       [-0.02219595],
       [ 0.00554831],
       [-0.01773969],
       [ 0.00638051],
       [-0.00545195]])

In [53]:
newshift.reshape(1, -1) - pcaout.mean_ @ pcaout.components_.T

array([[21.27373485,  8.7393026 ,  0.2992803 ,  0.37827679,  0.18731756,
         0.10342197, -0.09705182,  0.27810637]])

In [45]:
pcaout.components_

array([[-0.4801615 , -0.48537917, -0.42692001, -0.38256614, -0.2923779 ,
        -0.2376041 , -0.20148819, -0.15065328],
       [ 0.33591429,  0.27616761,  0.13117867, -0.01096953, -0.23305908,
        -0.37804252, -0.49697954, -0.59105289],
       [-0.59753432, -0.1682775 ,  0.45065081,  0.4175572 ,  0.3099407 ,
         0.02968238, -0.14486372, -0.34534833],
       [-0.4746034 ,  0.73959838, -0.25024972, -0.06548855, -0.19437978,
         0.33868038, -0.06686374, -0.06223758],
       [-0.16191086,  0.12843317, -0.06804262,  0.56380593, -0.36608978,
        -0.5732779 ,  0.04940152,  0.41191392],
       [ 0.19484091, -0.16966521, -0.60138328,  0.56425675, -0.00614744,
         0.2603976 ,  0.15067434, -0.40330602],
       [ 0.05847031, -0.24449361,  0.37237236,  0.10677777, -0.74361596,
         0.48010158, -0.05002982,  0.02786088],
       [-0.08193894,  0.0880735 ,  0.17282234, -0.16497197, -0.19831206,
        -0.24102016,  0.81197989, -0.41438633]])